### ISSUE TITLE
Add scripts to run vue client using docker

### ISSUE THREAD

**Issue by ianco** [bcgov/orgbook-bc-client-vue#103]

**Comment by amanji** [comment]
Are we missing anything that's not already in the `/docker` folder? https://github.com/bcgov/orgbook-bc-client-vue/tree/main/docker

**Comment by ianco** [comment]
> Are we missing anything that's not already in the `/docker` folder? https://github.com/bcgov/orgbook-bc-client-vue/tree/main/docker

I guess I'm just blind :-D
