### ISSUE TITLE
Registration Type Translations

### ISSUE THREAD

**Issue by swcurran** [bcgov/orgbook-bc-client-vue#29]
The content for the translations of the Registration Event Types can be found here:

https://docs.google.com/spreadsheets/d/1gfn6UACE88vcPYCEI96GVHPLdGxMcKGvZp6ZM33s0kg/edit?usp=sharing

Please review and determine how best to get this added to the BC OrgBook Client Vue.

**Comment by swcurran** [comment]
My thought (for what it is worth) is that we have two approaches:

We could put these in the set of translations in the Issuer Registration process, as that would be cleanest.  If we did that, perhaps we need a way to flag in the issuer registration process the set of claims/attributes that are subject to translation.  Or do we just make it default for all claims? 

Alternatively, since this is the BC OrgBook interface, we can just put the translations into the interface itself and just have the translation list stored in the source code.

One further complexity to consider.  The list evolves over time. How do we add new translations to the list?  How do we detect that there was no translation made, and the raw value was used, which would (in the case) be unexpected, and a sign that something needs to be done.  Fun, eh?

Please decide on an approach and summarize it here before proceeding.

@wadeking98 @amanji @ianco

**Comment by ianco** [comment]
Event and filing type descriptions used to be in the i18n properties for the orgbook client:

https://github.com/bcgov/aries-vcr/blob/1.6.0/client/themes/bcgov/assets/i18n/en.json#L129

Note that there are language-specific values for a number of the BC Reg codes.

**Comment by amanji** [comment]
I agree that there is a tradeoff between the two approaches. In terms of long-term maintenance I would be highly in favour of user-specified translations rather than we track them in i18n. The way the current meta data is setup, we have translations for claim keys. We'd need to somehow add the same support for claim values for this case.

**Comment by wadeking98** [comment]
I agree with Ian, using the en.json approach is easiest. Currently we have some translations set up in the en.json file. @amanji  already setup the logic to translate raw values so I would like to leverage that approach sice the functionality is already there.
