### ISSUE TITLE
Need text for "Entity Result" dialog boxes

### ISSUE THREAD

**Issue by swcurran** [bcgov/orgbook-bc-client-vue#31]
From the list of things left to do, this item is:

> The dialog boxes have been implemented, but we need the content for the entity page dialog boxes. The wireframe does not provide any usable content for dialog boxes. We need to dicuss what content to place in the entity dialog boxes

Please provide a sample or link to an example of this.  I'm not clear what is needed and where.

**Comment by swcurran** [comment]
Let's assume they are popups.  Could you expound, pretty please?

**Comment by swcurran** [comment]
Is this issue completed/closed?

**Comment by wadeking98** [comment]
Not yet, I've sent out an email to Dwayne Gordon regarding item 1 on the list. Item 1 is the only remaining issue that needs to be addressed

**Comment by DJ-Gordon** [comment]
We’ve got tool tips for most entity types on the name request application… bcregistry.ca/namerequest  Will these work?
 
If you click on View all business types, you’ll get a list of entity types. 

![CleanShot 2021-11-17 at 16 43 29](https://user-images.githubusercontent.com/19692310/142322117-fff3f965-991c-4fe1-8fc6-5c0d36f1db59.png)

![CleanShot 2021-11-17 at 16 44 43](https://user-images.githubusercontent.com/19692310/142322893-0d3402ec-1501-4a3b-9265-d0490178088b.png)

**Comment by wadeking98** [comment]
I think that will work, what are your thoughts @swcurran and @alexgmetcalf ?
