### ISSUE TITLE
Contact page text -- How to add your organization to OrgBook

### ISSUE THREAD

**Issue by swcurran** [bcgov/orgbook-bc-client-vue#32]
Please use the following text:

> Not finding your organization in OrgBook BC?
> 
> One reason you might not be finding the entity for which you are searching is that the organization has not been registered with BC Registries. If the organization has been registered, search for the BC Registries ID (it has a format like "FM1234567"). You can also try searching by your 9-digit Business Number from CRA, if that number is registered with BC Registries.
>
> If you need to register the organization, these links may help. [Register your business in BC](https://www2.gov.bc.ca/gov/content/employment-business/business/managing-a-business/permits-licences/businesses-incorporated-companies) or follow the full [step-by-step guide to starting a BC business](https://www2.gov.bc.ca/gov/content/employment-business/business/managing-a-business/starting-a-business).
> 
> If you need additional information, please contact the BC Registries Help Desk via email bcregistries@gov.bc.ca, or by calling the BC Registries Help Desk at 1-800-663-6102.

**Comment by wadeking98** [comment]
OK - simple change
