### ISSUE TITLE
Get BC Gov favicon

### ISSUE THREAD

**Issue by swcurran** [bcgov/orgbook-bc-client-vue#35]
We are currently using the default Vue icons, but should be using BC Gov ones.

@CharlesMacpherson -- same as previous. Should be with Dwayne to resolve, but I don't know his GitHub handle. Please help if you know how or pass this issue to Some One Else.

Thanks

**Comment by amanji** [comment]
This is the list if icons we will need
<img width="343" alt="Screen Shot 2021-10-06 at 8 46 56 AM" src="https://user-images.githubusercontent.com/5605464/136238315-16cc79b9-f2cf-4c4b-ace4-a65832675138.png">

**Comment by DJ-Gordon** [comment]
This is from Dwayne. For test

**Comment by DJ-Gordon** [comment]
This should have what you need: https://github.com/bcgov/sbc-auth/tree/main/auth-web/public/img/icons

**Comment by WadeBarnes** [comment]
@amanji, @wadeking98 had submitted this PR; https://github.com/bcgov/orgbook-bc-client-vue/pull/66

It had most of the icons, but is missing some of the `apple-touch` ones.  The link @DJ-Gordon supplied above has a more complete set of icons.  Could you please update the icons with the set from the link please.
