### ISSUE TITLE
How was your experience buttons in footer

### ISSUE THREAD

**Issue by swcurran** [bcgov/orgbook-bc-client-vue#36]
Assuming this is not too difficult, here is what I suggest for the up and down arrows.

- Up -- just record the action such that we can see it in the analytics.
- Down -- record the action so that we can see it in the analytics, and popup:

"Sorry you didn't have a great experience.  Would you like to contact us and submit a suggestion or question about the service?"

Include a "Yes" / "No" (or whatever you think...) and if they say yes, send them to the contact us page.

If possible, do NOT show the "How was your experience" button on the Contact page.

**Comment by swcurran** [comment]
The analytics I was proposing were just the "Google Analytics-type" (we use an alternative) tracking of URLs that are hit. That's one approach.  The other is just to have the Like/Dislike logos, have an endpoint and in a database track the vote (like/dislike) and date/time.   Nice to have would be to only count a vote once per "user session", if it is possible to track such a thing in a trivial way.

We definitely can't have the current two questions with nothing to click.  We'd be much better off with nothing.

**Comment by wadeking98** [comment]
turns out there's a bit more to the wireframe than I thought. I missed this part here:
![image](https://user-images.githubusercontent.com/36937407/135678044-32ecb77d-446c-4d93-8c16-ffb1048fe912.png)
Seeing as we have user input forms here, I think we will need a new endpoint
