### ISSUE TITLE
Translations not being applied for the Credential Type

### ISSUE THREAD

**Issue by swcurran** [bcgov/orgbook-bc-client-vue#69]
On this page: https://frontend-v2-prod.apps.silver.devops.gov.bc.ca/about/orgbook-data

The BC Registries credential types are not being translated (see image).  Please fix this and see if we can make sure this is not a problem elsewhere?  It's odd that the non-Registries ones are working on this same screen.

![image](https://user-images.githubusercontent.com/1018050/146282148-b118ea2b-7828-4d3c-9ece-8f2794a82cd6.png)

**Comment by swcurran** [comment]
I think this is needed for launch, but it can be a follow if needed.  But please at least scope the issue -- is this big?

**Comment by amanji** [comment]
This requires an update to the BC Registries Schema Metadata. I'm guessing Dwayne Gordon or @ianco would probably need to reach out to the owners to update them? Unless we can do that ourselves

**Comment by amanji** [comment]
The remaining types show up as they do because that is the actual Schema name authored by the issuers. The fallback on this page is to show Schema name if a Metadata localization is not provided.

**Comment by ianco** [comment]
> This requires an update to the BC Registries Schema Metadata. I'm guessing Dwayne Gordon or @ianco would probably need to reach out to the owners to update them? Unless we can do that ourselves

Have the latest BC Reg updates been applied?  We can make the changes here:  https://github.com/bcgov/von-bc-registries-agent

Ping me if you want to chat about what we need to change

**Comment by WadeBarnes** [comment]
@ianco, Yes the latest updates to BC Reg are deployed to all of the environments.

**Comment by WadeBarnes** [comment]
Fixed in `test`; https://frontend-v2-test.apps.silver.devops.gov.bc.ca/about/orgbook-data
