### ISSUE TITLE
Footer links not linking to the correct content.

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/orgbook-bc-client-vue#72]
The links in the application's footer all link back to the search page rather than the expected content.

Example site: https://frontend-v2-test.apps.silver.devops.gov.bc.ca/
![image](https://user-images.githubusercontent.com/10504350/146608137-8c836d3c-b3ba-4efb-b51b-1b733b50bf0e.png)

They should link to the same content as they do in the existing version of the OrgBook; https://orgbook.gov.bc.ca/en/home

Disclaimer: https://www2.gov.bc.ca/gov/content/home/disclaimer
Privacy: https://www2.gov.bc.ca/gov/content/home/privacy
Accessibility: https://www2.gov.bc.ca/gov/content/home/accessible-government
Copyright: https://www2.gov.bc.ca/gov/content/home/copyright

**Comment by swcurran** [comment]
@amanji -- can you do a quick fix for this?

**Comment by WadeBarnes** [comment]
Fixed in `test`
