### ISSUE TITLE
Some Registration Type descriptions are not being translated correctly.

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/orgbook-bc-client-vue#75]
Example: https://frontend-v2-test.apps.silver.devops.gov.bc.ca/entity/PA0000357

![image](https://user-images.githubusercontent.com/10504350/146610162-993aaf93-cd65-4e0f-bad9-f61ad18e0da2.png)

**Comment by swcurran** [comment]
@amanji can you fix this one?  If not, please assign to @wadeking98 for post launch cleanup.

**Comment by amanji** [comment]
If it's just this event type missing in the translation we'll add it for now. Likely will need to pull every unique registration type present in the DB and ensure that we have added entries for all of them.

**Comment by WadeBarnes** [comment]
Fixed in `test`.
