### ISSUE TITLE
Issuers and Credential not showing up in PROD

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/orgbook-bc-client-vue#84]
Observed: https://frontend-v2-prod.apps.silver.devops.gov.bc.ca/about/orgbook-data

![image](https://user-images.githubusercontent.com/10504350/146774584-f3183f4a-ab59-4d61-8f49-bda7941ebe38.png)

Expected: https://frontend-v2-test.apps.silver.devops.gov.bc.ca/about/orgbook-data
- Minus the duplicate BC Mines Act Permit

![image](https://user-images.githubusercontent.com/10504350/146774619-1fe3132c-27b1-4ac2-be66-894a57fd55c2.png)

**Comment by WadeBarnes** [comment]
The data is coming back in the query:
![image](https://user-images.githubusercontent.com/10504350/146776461-e4ba67c6-637c-4b77-a5ec-b47f9079aaec.png)

**Comment by WadeBarnes** [comment]
An error reading the data:
![image](https://user-images.githubusercontent.com/10504350/146776657-dbae55f2-3b2f-4c06-8646-9d857bfff108.png)

**Comment by WadeBarnes** [comment]
Some of the credential types are missing the `schema_label` fields.
![image](https://user-images.githubusercontent.com/10504350/146777279-36ea0e1e-f4ac-47c0-a00a-51f0cabbe7a0.png)

The code should be defaulting to the `description` field in these cases.

**Comment by WadeBarnes** [comment]
Looks like it's the `Buy BC Logo License` data that is tripping up the code:

In **test**:
![image](https://user-images.githubusercontent.com/10504350/146780160-306b1423-07ca-46ab-86ef-193e0bdd0563.png)

In **prod**:
![image](https://user-images.githubusercontent.com/10504350/146780237-404f2809-5f7d-45bf-b0f5-179c81176f55.png)

**Comment by WadeBarnes** [comment]
@esune, Can you provide the schemas for Buy BC the are registered in their `test` and `prod` environments?  Specifically interested in whether they define the `schema_label` and if so how they're defining it.

**Comment by WadeBarnes** [comment]
This issue does not affect the display of the description on the search results page:

![image](https://user-images.githubusercontent.com/10504350/146782067-2e795d52-2ff8-4f41-8d8e-8a45ec1eb909.png)

**Comment by esune** [comment]
@WadeBarnes it looks like you got it covered, let me know if you still need more info.

**Comment by WadeBarnes** [comment]
@esune, I still would like the schemas, I want to compare what they are registering to the data we have in our various environments.  Since their repo is private I don't have access.

**Comment by WadeBarnes** [comment]
Tested in `prod`, immediate issue (the display) has been resolved.

**Comment by WadeBarnes** [comment]
The `credential type` registered in `prod` is the correct one; the one registered by the Buy BC controller.  The one in `test` was the one that was manually modified.  I restarted the Buy BC controller in `test` and it re-registered itself, the resulting `credential type` matched the one in `prod`.
