### ISSUE TITLE
Difference in auto-complete results - v1 vs v2

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/orgbook-bc-client-vue#85]
v2 results look like this:

![image](https://user-images.githubusercontent.com/10504350/146775280-15d8bbad-3f00-46d3-8cf2-59b78c19fcdb.png)

v1 results look like this:

![image](https://user-images.githubusercontent.com/10504350/146775339-c097156e-de2c-4bb2-8b87-9fc418a7313d.png)

Yet the search results remain the same:

![image](https://user-images.githubusercontent.com/10504350/146775682-6359c088-d195-4cd6-aa0a-fb79ea0e96b9.png)

Is this expected behavior?

**Comment by amanji** [comment]
This may be due to the internal implementation of Vuetify's autocomplete. I can see 10 results returned from the API response but only the closest matching results are displayed

**Comment by WadeBarnes** [comment]
Tested in `prod`.  Fixed, auto-complete results now match with the original OrgBook.
