### ISSUE TITLE
Relationship links do not link to the corresponding record

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/orgbook-bc-client-vue#86]
The relationship records on the company details screen do not link to the corresponding company record as expected, rather they just open a drop down to display a little more info.

Example: https://frontend-v2-prod.apps.silver.devops.gov.bc.ca/entity/BC0722797

![image](https://user-images.githubusercontent.com/10504350/146783118-d5c987be-a1a4-449f-ba6a-9cadf430b09e.png)

I would expect the link to open to this record:
![image](https://user-images.githubusercontent.com/10504350/146783277-79474208-c436-4845-ac63-1cff29f0a2e4.png)

Instead it does this:
![image](https://user-images.githubusercontent.com/10504350/146783344-c47a7e4c-ec98-4fec-ab66-a0eb83de6fa8.png)

**Comment by WadeBarnes** [comment]
@swcurran, what's your opinion on releasing without a fix for this one?

**Comment by swcurran** [comment]
I think it is fine to leave for launch.  Needed, but we can get away with it for now.

**Comment by WadeBarnes** [comment]
I think @amanji is already working on a fix for this.

**Comment by WadeBarnes** [comment]
Fixed, tested in `prod`.  There are some fairly minor usability side effects that will need to be cleaned up.  I'll enter separate tickets for them.
