### ISSUE TITLE
Change "In Good Standing" label on organization screen to "Active" and "Historical"

### ISSUE THREAD

**Issue by swcurran** [bcgov/orgbook-bc-client-vue#91]
The term "In Good Standing" has legal ramifications that we can't imply on the site, and the data we are using to display the data is not sufficient.  Please change the display to say "Active" and "Historical" instead of "In Good Standing" and whatever other term we are using.

If we are using "Archived" let me know and we can discuss.  We need to be consistent in using the same term across the site when we mean "A dissolved organization" -- and a different term then when we are talking about a "credential that is no longer active".

This has to be done before launch.  Sorry for the late notice.

**Comment by WadeBarnes** [comment]
Fixed, tested in `prod`.
